version: '3.8'            # compose file version 3.8 is quite new and should work

services:
  app:                    # The name of the service, can be anything
    image: todov2         # name of img
    build: .              # Declares where to build if image is not found
    ports:                # Declares the ports to publish
      - 3000:3000