name: Periodic health check
on: 
  schedule:
    - cron: '20****'
      
jobs:
  url_checker:
    runs-on: ubuntu-latest
    steps:
      - name: check deployed url
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://fso-pokedex-2022.fly.dev/health
          max-attempts: 3
          retry-delay: 5s
