name: Phonebook Deployment pipeline

on: 
  push: 
    branches: 
      - main
      
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          node-version: '18.9.1'
          
      - name: npm install
        working-directory: part11/phonebook-fullstack
        run: npm install
        
      - name: lint
        working-directory: part11/phonebook-fullstack
        run: npm run lint
        
      - name: build
        working-directory: part11/phonebook-fullstack
        run: npm run build

      - name: e2e test
        uses: cypress-io/github-action@v4
        with:
          working-directory: part11/phonebook-fullstack
          start: npm run start
          wait-on: http://localhost:3001
               
    
