name: Deployment pipeline

on: 
  push: 
    branches: 
      - main

jobs:
  simple_deployment_pipe:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: npm install
        working-directory: part11/full-stack-open-pokedex
        run: npm install
      - name: lint
        working-directory: part11/full-stack-open-pokedex
        run: npm run eslint
      - name: test
        working-directory: part11/full-stack-open-pokedex
        run: npm run test
      - name: build
        working-directory: part11/full-stack-open-pokedex
        run: npm run build
      
