name: Deployment pipeline

on: 
  push: 
    branches: 
      - main

jobs:
  simple_deployment_pipe:
    runs-on: macOS-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: npm install
        working-directory: full-stack-open-pokedex
        run: npm install #install dependencies
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
