name: Deployment pipeline

on: 
  push: 
    branches: 
      - main
      
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  simple_deployment_pipe:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          node-version: '16'
      - name: npm install
        working-directory: part11/full-stack-open-pokedex
        run: npm install
      - name: lint
        working-directory: part11/full-stack-open-pokedex
        run: npm run eslint
      - name: test unit
        working-directory: part11/full-stack-open-pokedex
        run: npm run test
      - name: e2e test
        uses: cypress-io/github-action@v4
        with:
          working-directory: part11/full-stack-open-pokedex
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: build
        working-directory: part11/full-stack-open-pokedex
        run: npm run build
      - name: deploy
        working-directory: part11/full-stack-open-pokedex
        run: flyctl deploy --remote-only
