name: Deployment pipeline

on: 
  push: 
    branches: 
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
      
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  simple_deployment_pipe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          node-version: '16'
      - name: npm install
        working-directory: part11/full-stack-open-pokedex
        run: npm install
      - name: lint
        working-directory: part11/full-stack-open-pokedex
        run: npm run eslint
      - name: test unit
        working-directory: part11/full-stack-open-pokedex
        run: npm run test
      - name: e2e test
        uses: cypress-io/github-action@v4
        with:
          working-directory: part11/full-stack-open-pokedex
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:8080
      - name: build
        working-directory: part11/full-stack-open-pokedex
        run: npm run build
      - name: deploy
        if: ${{ github.event_name == 'push' }}
        working-directory: part11/full-stack-open-pokedex
        run: flyctl deploy --remote-only
        
  tag_release:
    needs: [simple_deployment_pipe]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Bump version and push tag
      - uses: anothrNick/github-tag-action@1.36.0
      - env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          
