name: Deployment pipeline

on: 
  push: 
    branches: 
      -main

jobs:
  simple_deployment_pipe:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3 #this action is a public one we're reusing
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install #install dependencies
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
